// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjdfkxkwgwhaydtnqvdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqZGZreGt3Z3doYXlkdG5xdmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjU2MTEsImV4cCI6MjA2MTYwMTYxMX0.EPydfxjV39f22g-y88plrQQINxYamqv7YDLcb05BPrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);